### ISSUE TITLE
Request: Support for hold_action / double_tap_action

### ISSUE THREAD

**Issue by syphernl** [DBuit/Homekit-panel-card#10]
Right now only `tap_action` (single click) is implemented. However I'd like also like to be able to "hold" an element to call another service (e.g. `browser_mod.popup`). Right now it simply opens the "more-info" dialog of HASS. Also might be nice to have `double_tap_action` too.

Could these be added?

**Comment by DBuit** [comment]
Hello,
Yes i can add this!
For now you can already set custom pop-up on the hold action it is in de readme. It works the same way as browser mod IT uses Thomas lovens card tools

**Comment by DBuit** [comment]
@syphernl i released V0.3 and you can now customize the hold and double tap action!

**Comment by syphernl** [comment]
Great, thanks!
