### ISSUE TITLE
Can you create a version of this that we can use for an Input_Number? 

### ISSUE THREAD

**Issue by alanthewild** [DBuit/Homekit-panel-card#101]
I am using Thomas Loven's slider-entity-row to display an Input_number that I use for Volume control.

Would be really handy to have a homekit styled slider for input numbers.
It would need to use the values from the input_number rather than the 0-100% that your light-popup-card uses.
eg. one of mine is setup for volume like so:
```
avr_volume:
  name: Lounge
  icon: mdi:volume-medium
  min: -80
  max: -10
  step: 0.5
  unit_of_measurement: dB

There is no Off or On state, just a value between -80 and -10 in this case.

**Comment by jnpetersen** [comment]
@alanthewild  so are you looking for an entry box to click in to type a number, or maybe a +/- to increate the "slider" value?  I'm looking at trying to contribute and help, so I just want to understand what you are looking for.

**Comment by DBuit** [comment]
This is not an issue for the homekit card
