### ISSUE TITLE
Feature Request: add box-shadow for button to customizable css variables.

### ISSUE THREAD

**Issue by dvbit** [DBuit/Homekit-panel-card#105]
Hi
I would like to achieve an effect like this one:
https://codepen.io/kanhaiyasharma/pen/vYEZZvd
This is done using box-shadow
Could it be added to the variables in next release?

Thanks for the great work!

**Comment by DBuit** [comment]
Hello @dvbit ,

no need to wait for a variable, you can add this to the style part of the card like this:
```
- type: "custom:homekit-card"
        style: |
          homekit-button.button {
              box-shadow: 9px 9px 16px rgb(163,177,198,0.6), -9px -9px 16px  rgba(255,255,255, 0.5)!important;
          }
```
