### ISSUE TITLE
Changing column spacing

### ISSUE THREAD

**Issue by lukewelch** [DBuit/Homekit-panel-card#107]
Hi 

Is it possible to change the spacing between columns? and also change the spacing between the top of the screen and the top of the first row? 

thanks

**Comment by DBuit** [comment]
Hello,

spacing between columns and tiles is not possible atm. The amount of tiles in a column that you set in your config is used to calculate the width of the column so if you change the spacing with the style option this would break and not all tiles will fit on 1 row.

The space above a row can be changed with the style option try this for the first row of tiles on your dashboard:
```
- type: "custom:homekit-card"
        style: |
          .row:first-child {
               padding-top:100px!important;  //Adds 100px of space above the first row
               padding-bottom:100px!important; //Adds 100px of space below the first row
           }
```

**Comment by clearwave1** [comment]
Please add all of the styles that are possible to your documentation.
