### ISSUE TITLE
break in config not working

### ISSUE THREAD

**Issue by jnpetersen** [DBuit/Homekit-panel-card#108]
I had in my panel code I would use the follow:

`- break`

in order to space things out so that it would move to the next column.  Now I'm getting this error message in red

```
Config is not an object
break
```

Is there a reason why this doesn't work anymore, or how can I probably handle columns?

**Comment by jnpetersen** [comment]
Used to look like this:

![Screen Shot 2021-04-05 at 10 04 49 AM](https://user-images.githubusercontent.com/963185/113601693-845b4700-95f6-11eb-910d-5e79157104a2.png)

Now looks like this:

![Screen Shot 2021-04-05 at 10 05 06 AM](https://user-images.githubusercontent.com/963185/113601725-8fae7280-95f6-11eb-8705-8c9f216cfe7a.png)

**Comment by DBuit** [comment]
Hello,

As far as i can remember break never was  a thing 🤔
But to make it look like your first screenshot look on the info on github page and look for `enableColumns`
