### ISSUE TITLE
Feature Request: Haptics on Mobile?

### ISSUE THREAD

**Issue by EliotHertenstein** [DBuit/Homekit-panel-card#109]
Usually mobile users get haptic feedback when holding down on a button, however that's taken away when using homekit. Is there any way that could be added back?

**Comment by ksmarty** [comment]
I'd like to reopen this issue as there is no way to enable haptic feedback globally, on a row-by-row basis, or on an individual entity without overwriting the tap action. If I'm mistaken please let me know. Thank you!
