### ISSUE TITLE
noPadding resizes tile after adjusting tile settings

### ISSUE THREAD

**Issue by skank01** [DBuit/Homekit-panel-card#121]
I adjusted width and heigth of my tiles ..
As i did my custom button card is doing strange stuff
As you can see here, my second button is normal size but the custom button doesnt fill the tile
[url=https://imgbb.com/]![](upload://ljWo63SLqS9kZPcYFJn5kdE5Jjt.jpeg)[/url]

However i normally add "noPadding: true", but when i do now, the tile size gets bigger?
I have no idea why
[url=https://imgbb.com/]![](upload://uP2EarCA9stWNc0lDTUmwN3wlqW.jpeg)[/url]

Any idea why? It seems after changing the style of the homekit button (especialaly width and heigth), the noPadding settings doenst change with it?

Here's my adjusted tile setting
[code]
style: |
      :host {
        --tile-background: rgb(255, 255, 255);
        --tile-icon-size: 40px;
        --tile-border-radius: 10px;
        --tile-width: 85px;
        --tile-height: 85px;
        --tile-on-background: #464446;
        --tile-name-text-color: #464446;
        --tile-on-name-text-color: rgba(255, 255, 255, 1);
        --tile-state-text-color: rgba(0, 0, 0, 0.4);
        --tile-on-state-text-color: rgba(0, 0, 0, 1);
        --tile-state-changed-text-color: rgb(134, 134, 134);
        --tile-unavailable-state-text-color: rgba(255, 255, 255, 0,5);
        --tile-value-text-color: rgba(255, 0, 0, 1);
        --tile-icon-color: #464446;
        --tile-on-icon-color: rgba(255, 255, 255, 1);
        --tile-width-mobile: 85px;
        --tile-height-mobile: 85px;
      }  
      .button-inner .icon {
            width:55px;
            height:55px;
          }
          .button-inner .icon ha-icon {
            width: 40px;
            height:40px;
          }
[/code]

**Comment by mvanlijden** [comment]
I also found this as an error. But it seems that once you enable the noPadding, any tile width and height override you did on card even the main card level are ignored and you are stuck with the basic 100x100px size

**Comment by DBuit** [comment]
This is fixed in https://github.com/DBuit/Homekit-panel-card/releases/tag/0.6.2
