### ISSUE TITLE
Can't get it working with Home Assistant Cast 

### ISSUE THREAD

**Issue by rubenni** [DBuit/Homekit-panel-card#122]
Hello! First of all: thank you for this awesome panel card! It works perfectly in a regular browser or in the HA app. Although I wanted to use it on my Nest Hub 2 too. This should be possible with Home Assistant Cast. Lots of other custom cards (like custom button card) do work with HA Cast. I get on my Nest Hub that the custom element does not exist, although I entered it in the resources tab in the settings like all the other custom cards. So it seems that this panel card doesn't work on it. I went to the [FAQ ](https://cast.home-assistant.io/faq.html ) of HA Cast and saw that the most common problem is that LitElement is extracted from an element that is not available on the page. 
I've never made a card for HA before but I see on line 1224, LitElement is defined. But I'm not sure how it should look. 
I'm also not sure if the basic version of the card relies on Browser Mod, because Browser Mod doesn't work on HA Cast either atm.

Would someone mind taking a closer look? Let me know if I can help with something like testing!
Regards!

**Comment by DBuit** [comment]
This is fixed in https://github.com/DBuit/Homekit-panel-card/releases/tag/0.6.2
