### ISSUE TITLE
0.4.2 ignores titleColor

### ISSUE THREAD

**Issue by acateon** [DBuit/Homekit-panel-card#20]
![title](https://user-images.githubusercontent.com/14361705/73647681-4a9e5180-467c-11ea-80ae-5b28c61fc59d.png)

        title: "Övre Husargatan 9"
        useBrightness: false
        useTemperature: false
        titleColor: "#FFF"
        enableColumns: true
        statePositionTop: true
        horizontalScroll: false
        tileHoldAnimation: true

**Comment by DBuit** [comment]
Hi @acateon 
The part that is black is not the titleColor, use rulesColor to set the color
