### ISSUE TITLE
Json error with mini-media-player as custom card

### ISSUE THREAD

**Issue by acateon** [DBuit/Homekit-panel-card#21]
Rendering the card works fine but when clicking on play, pause etc it trigger the following errors from homekit-panel-card.js
[192.168.1.10-1580804143501.log](https://github.com/DBuit/Homekit-panel-card/files/4152083/192.168.1.10-1580804143501.log)

**Comment by DBuit** [comment]
@acateon released new version with fix for this error and enables mouse actions on tile that loads another card
