### ISSUE TITLE
iOS Safari rendering width

### ISSUE THREAD

**Issue by acateon** [DBuit/Homekit-panel-card#22]
Saw that this was an issue on the HA forum and reported as fixed but as seen in the attached screen shot from my iPhone it still exists. 

Works fine while simulating iPhone X in Chrome, and works as expected in Safari on Mac.

![IMG_155F026B49DB-1](https://user-images.githubusercontent.com/14361705/73846710-43ff0e00-4825-11ea-940f-e91bf163be27.jpeg)

**Comment by DBuit** [comment]
Hi @acateon thank for mentioning. It is fixed in new release.
