### ISSUE TITLE
Text overflow in rules/templating 

### ISSUE THREAD

**Issue by acateon** [DBuit/Homekit-panel-card#27]
When a long text string is presented in the companion app the overflow wrecks the width. See image.

Is it possible to have a automatic line break or truncating?  
![IMG_E8F91912B1F9-1](https://user-images.githubusercontent.com/14361705/74134845-89d42180-4beb-11ea-9496-7a9a7f0d890f.jpeg)

**Comment by DBuit** [comment]
Hi @acateon,
just released new update with a fix for this problem.
