### ISSUE TITLE
Request: faster popup menu 

### ISSUE THREAD

**Issue by Tedsterh** [DBuit/Homekit-panel-card#28]
I don't suppose there is anyway to open the popup menu while holding the button. At the minute you have to press and hold then let go before the tile opens. Would it be possible to open the popup menu while the tile was being pressed so you knew when to let go?

**Comment by DBuit** [comment]
Hi @Tedsterh i would like that to but that won't work because on holding you will get a ghost click action when you release it which closes the pop-up.

What you can do is set `tileHoldAnimation` to true in your config which will animate the tile when you can release it.

**Comment by Tedsterh** [comment]
Hi @DBuit this works amazing, thank you!
