### ISSUE TITLE
Rules height - remove extra white space

### ISSUE THREAD

**Issue by acateon** [DBuit/Homekit-panel-card#29]
Is it possible to remove the extra whitespace/rows in the rules?

Se example below where there's extra whitespace. I would like to be able to set the height either in pixels, number of rows or that it defaults to the same spacing as it is between the title and rules section.

![whitespace](https://user-images.githubusercontent.com/14361705/74921155-a5021680-53cd-11ea-8877-99f29dfa0057.png)

**Comment by DBuit** [comment]
Hi @acateon ,

I just released update and now you can set `--min-header-height` in the style section to set the minimal height of the rules.
