### ISSUE TITLE
Roller shutter popup card (homekit style)

### ISSUE THREAD

**Issue by socialsubs** [DBuit/Homekit-panel-card#34]
It would be nice to have a roller shutter popup card to easily manage this type of entity.

Thanks for your excellent work!!

**Comment by CervDotBe** [comment]
> It would be nice to have a roller shutter popup card to easily manage this type of entity.
> 
> Thanks for your excellent work!!
He already created this cover-popup-card: https://github.com/DBuit/cover-popup-card

**Comment by socialsubs** [comment]
> He already created this cover-popup-card: https://github.com/DBuit/cover-popup-card

Many thanks for your reply.
