### ISSUE TITLE
Request: brightness slider

### ISSUE THREAD

**Issue by capstan1** [DBuit/Homekit-panel-card#38]
I've got a new feature request: brightness slider on the card. The popup card is nice, but having the slider right inside the tile would be HUGE. This would be especially helpful with wider cards. I made this mockup:
![1](https://user-images.githubusercontent.com/17147867/77839921-aa4b4180-7181-11ea-9f72-21ffc2d382de.png)

If wanted, this could also show the color (not so nice with my current theme, but you get the idea):
![2](https://user-images.githubusercontent.com/17147867/77839923-b9ca8a80-7181-11ea-9b1f-4496dadac5f4.png)

What do you think?

**Comment by DBuit** [comment]
Hi man,

Looks cool i'm gonna try to make an working example. i think i can be hard to use the slider with the text on top of it need to try this.

**Comment by DBuit** [comment]
Made a working example in html/css: https://codepen.io/dbuit/pen/MWwLOBx
So it could work

**Comment by capstan1** [comment]
Wow that was fast and it looks gorgeous!
Only downside I could think off: How would one toggle the lights? You could "block" the tapping on the bar for brightness adjustments (just swiping adjusts brightness, tapping toggles.
Hue uses an additional switch for a similar concept: https://youtu.be/VOBo_UAplQQ?t=89
Not sure if that is what you are going for.

But thanks again for even considering my concepts and being so quick! Definitely will drop yome coffees when the paycheck arrives!

**Comment by DBuit** [comment]
@capstan1 

Hi i just released beta version with this implemented in the card if you wanna test it out :)

**Comment by capstan1** [comment]
Wow thats great! Just How what I was thinking! It is so convenient like this! Also great how you found a solution for the "tapping issue".

I uncovered some bugs, though:

-  wider cards don't use the whole width for the slider. The last part is never used. For normal sized cards it is used, though: 
![image](https://user-images.githubusercontent.com/17147867/84058789-04eeee00-a9ba-11ea-9561-b92c2d4916af.png)

- If the light is turned of, the slider knob moves to the middle. Looks weird if you turn it off with sliding it to the far left and it just jumps to the middle
![image](https://user-images.githubusercontent.com/17147867/84059002-3a93d700-a9ba-11ea-8a7f-70dad253b5e9.png)
(However, if I turn a light off first by tapping and then move the slider all the way to the left it stays there.)


Do you think global variables for some of the values can be implemented in the future? For example, I'd like to use the slider, wider and halfheight for all cards.

Thanks again! You're great!

**Comment by DBuit** [comment]
Hi,

just released new version, this fixes the width and height of the slider when using wider of higher option.
