### ISSUE TITLE
Issues with HACD Installation in combination with HA 0.107 new Ressource manager 

### ISSUE THREAD

**Issue by Baumtreter** [DBuit/Homekit-panel-card#39]
Hi,

If I install the card via HACS and put the HACS Ressource path into the new Ressource Manager of Home Assistant it's recognized as unknown. 

I need to install it manually and put the "Manual Install" Ressource into the Manager. 

Is there a fix planned?

**Comment by Phibins** [comment]
I installed with Hacs a few days ago with no issue re: Ressource Manager.

Make sure you are adding 

`/hacsfiles/Homekit-panel-card/homekit-panel-card.js`

The manual resource url will look different.

**Comment by DBuit** [comment]
HACS changed i will update the readme today
