### ISSUE TITLE
Idea's to add to card

### ISSUE THREAD

**Issue by DBuit** [DBuit/Homekit-panel-card#4]
- [ ] Camera tile (https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/1/4/1483c756843335ad04434834011995c4276cfe29.jpeg)
- [x] iphone hold for pop-up improvement, check deep-press mod compatible?
- [x] Enable overwrite with tap_action for default toggle on tap for lights and switches
- [ ] render template for rules without admin rights?

**Comment by slipx06** [comment]
If you get a chance please consider adding support for fan speed control. 

![image](https://user-images.githubusercontent.com/7227275/72666386-5fdb7500-3a1a-11ea-848e-4b7b052bd72e.png)

![image](https://user-images.githubusercontent.com/7227275/72666397-797cbc80-3a1a-11ea-9c3a-394e3305b46f.png)
