### ISSUE TITLE
Request: popup on tap_action

### ISSUE THREAD

**Issue by CervDotBe** [DBuit/Homekit-panel-card#41]
Feature Request: have the possibility to call the custom popup on tap_action. Hold action is often to difficult for end users and it would be handy to call the custom popup on the tap_action. I know this might(?) be possible via the browser_mod, but it's interesting to not have this platform wide and only within the card.

**Comment by DBuit** [comment]
Hi @CervDotBe 

Maybe you already found it but this is already possible.
Check the actions part in the readme there you can set a tap_action on a tile. If you use browser_mod integration than this will give you a service to call a pop-up

**Comment by caseyjhol** [comment]
This does seem like this should be available by default.
