### ISSUE TITLE
Support for conditional tiles

### ISSUE THREAD

**Issue by CM000n** [DBuit/Homekit-panel-card#42]
I’d like to know if it is possible to display some tiles depending on certain conditions? 

For example, I have a garden irrigation system that is connected to a water tank. If the water level of the water tank is ok, I just want to have a switch tile in the frontend to turn the watering on and off. But if the water level is too low, I want the switch to be hidden and get a tile with a warning in its place.

Or another example. I use the integrated media-control card for the tiles of my media players and really like the look of it. But I just like that the media-control cards to be displayed when the media players play. When the media-players are off, I want to show something else for it

I couldn’t find anything regarding this question in the documentation.

**Comment by DBuit** [comment]
@CM000n i added some conditional stuff in V0.5
