### ISSUE TITLE
Not possible to deactivate Icon Brightness and temperature

### ISSUE THREAD

**Issue by Benekification** [DBuit/Homekit-panel-card#47]
The following General view settings are not honored by the config.
The icon color is always adapting to the Brightness of the lamp.
        useBrightness: false
        useTemperature: false

**Comment by skank01** [comment]
Having same issue
when i adjust brightness, the color of the icon changes, i cant keep it the same color

**Comment by DBuit** [comment]
@Benekification , @skank01 this is fixed in V0.4.9.5
