### ISSUE TITLE
[request] update of cover card

### ISSUE THREAD

**Issue by yvesfouquet4** [DBuit/Homekit-panel-card#51]
would it be possible to have a cover/blind card which cant be controlled without the need of a popup card like this:

![afbeelding](https://user-images.githubusercontent.com/8839059/81937784-5b078600-95f4-11ea-8b7f-733f57297d37.png)

**Comment by RedGuilhas** [comment]
Any update on this matter? I also would like very much for this feature.

**Comment by mnayef95** [comment]
Any update on this?
