### ISSUE TITLE
{request} Conditional background colr

### ISSUE THREAD

**Issue by Kouwe-sudo** [DBuit/Homekit-panel-card#56]
I think you've done a fine piece of work. And I also have the impression that you like it when people come up with sugessties. Since a madman can think of more than a programmer can handle, I have 3 wishes.

1. It would be great if you could work with thresholds. I mean that the backside of a tile gets a different colour when a certain value is reached. You can then see at a glance on your screen that something is going on. Think of the processor temperature above a certain value after which the background of the tile automatically turns red.
2. What would also be very nice in that context is that the background could blink. Think for example of a rain sensor. At actual precipitation, the background of the tile flashes blue.
3. With the popup card, it would be nice if you could also choose the colour of a circle with all the colours on it. Although there is already such a custom card from another developer, it doesn't really work well with your homekit-card. The popup works and you can choose any colour but you can't get back to the previous screen  without restarting the system.

**Comment by DBuit** [comment]
Hi @Kouwe-sudo 

point 1 and 2 are now possible with V0.5
point 3 is possible there are other cards that have that kind of cirlce and you can use it as a popup
