### ISSUE TITLE
Wrong css style for unit of measurement in graph tiles

### ISSUE THREAD

**Issue by holnburger** [DBuit/Homekit-panel-card#58]
Currently graph tiles are looking clean but the unit of measurement has a different format then the unit itself.

![image](https://user-images.githubusercontent.com/22478441/85106127-f6030980-b20b-11ea-8448-8454311e8583.png)

The `state__uom` class should have the same css attributes as `state__value` to look clean. Otherwise great looking integration :)

**Comment by DBuit** [comment]
Hi @holnburger 

thanks you for saying, i added the missing css in V0.4.9.5
