### ISSUE TITLE
Circle and temperature display in the new climate tile are not centered

### ISSUE THREAD

**Issue by CM000n** [DBuit/Homekit-panel-card#6]
Hello Dbuit, 
I have just installed version 0.2 of the Homekit-panel-card and I really like the new tiles for climate entities.
Sadly the Circle and temperature display in the new climate tile are not centered for me.
The circles have an elliptical shape and the text is too far down.:
![climatenannt](https://user-images.githubusercontent.com/7945681/72223470-590eb700-356f-11ea-88e3-76ab0adc1885.PNG)

**Comment by DBuit** [comment]
Hey man,
that doesn't look as it should be!
i Will do a fix release tomorrow morning!

**Comment by DBuit** [comment]
Hey man,
just released V0.2.1 which will fix the style of the thermostat tile :)
