### ISSUE TITLE
Error on Popup after Upgrade to 0.113

### ISSUE THREAD

**Issue by briis** [DBuit/Homekit-panel-card#69]
After upgrading to 0.113, I start getting the following error, when clicking a button that calls a Popup:

`https://MYIPADDRESS/hacsfiles/Homekit-panel-card/homekit-panel-card.js:1407:14 Uncaught TypeError: Cannot read property 'close' of undefined`

The popup never occurs, so I can no longer control my Media players and Switches that have popups.

**Comment by DBuit** [comment]
Hi @briis ,

The popups are possible with the use of card tools by thomasloven. 
He is working on an update to fix this. When this update it out i will update the card to fix this

**Comment by briis** [comment]
Perfect, thanks. And congratulations with your new baby.

**Comment by mmonkey** [comment]
@DBuit confirmed working again after latest update, but now on every popup `<div class="main-title">test</div>` is rendered.

**Comment by mmonkey** [comment]
@DBuit Also, settings on popups no longer display (i.e. light-popup-card `settings: true`)

**Comment by caseyjhol** [comment]
Also, it seems the popup is too big (when viewing in the browser on desktop), as it fills almost the entire window, so clicking outside of the popup to close it is made more difficult.

**Comment by DBuit** [comment]
I Will check the test title and the settings tomorrow.
@caseyjhol thuis is stille i bug in card tools it has a closePopup function buy thuis is not working at the moment

**Comment by briis** [comment]
It works for me now, thanks for fixing @DBuit. I will close this issue.
