### ISSUE TITLE
Ability to set smaller height

### ISSUE THREAD

**Issue by pineappeal** [DBuit/Homekit-panel-card#76]
This would be similar in concept to the aspect_ratio parameter of the `Button Card` card and the opposite of your card's current feature of setting `wider` as a parameter for tiles with more width. 
What I want to be able to do is (for example) have a row of tiles that are shorter in width so as to fill a small leftover space on mobile screen. I'm having trouble implementing `Button Card` to use its `aspect_ratio` parameter even inside a `vertical-stack`. Posted on the Community page but no luck so being able to do this natively from inside Homekit-panel-card would be awesome. 
Keep up the amazing work!

**Comment by DBuit** [comment]
Hi @pineappeal 

At the moment there is not smaller width, there is halfHeight option
