### ISSUE TITLE
Multiple State-controlled Icons

### ISSUE THREAD

**Issue by pineappeal** [DBuit/Homekit-panel-card#79]
Adding an optional parameter where the user can set the main tile icon to be reflect the state of an entity- either the main entity of the tile or another entity. The idea would be to allow the tile to reflect multiple state-controlled icons. 
I've attached a picture for illustration purposes - this is taken from a UI I had on a previous HA installation where I had icons for light, motion sensor and door contact sensor each reflecting an entity's state (for your inspiration 😄 )

![e1e807b6b96585495d1399d2d6fa063949cb946b](https://user-images.githubusercontent.com/2551480/91172772-0688a200-e6dd-11ea-8c57-142746bac398.png)

**Comment by diestake** [comment]
+1

**Comment by wtrbuit** [comment]
Let's discuss this.

What you are basically asking is to be able to get a tile which now represents 1 entity to have a tile where you can enter multiple (max 2 or 3) entities and show the icon for each of those entities in the tiles which reflect the status of the entity. Is that in short what you would like to have?

**Comment by DBuit** [comment]
@wtrbuit i think the idea is to have different icons for each state of 1 entity.
So simple one would be light entity and have a different icon for the on state and off state
But other entities could have more than 2 states.
