### ISSUE TITLE
Request: Status value top right corner

### ISSUE THREAD

**Issue by syphernl** [DBuit/Homekit-panel-card#8]
I'm trying to rebuild my dashboard so it matches something like this:

![](https://raw.githubusercontent.com/matt8707/hass-config/master/www/img/screen.png)

However, it uses a picture-elements-card and on+off pictures for each entity making it less practical to use. It also doesn't scale properly on multiple devices. 

Either way, what I do like of this interface is the status in the top-right corner (with the circular percentage). Is this something that could be added to this plugin?

**Comment by DBuit** [comment]
That is pretty Nice. 
I Will see what i can do :)

**Comment by DBuit** [comment]
@syphernl just release V0.3 and i also added option to move the extra state info like brightness and last_changed to top right corner in a circle like the example. you can set use `statePositionTop` for this.

**Comment by syphernl** [comment]
Awesome!
