### ISSUE TITLE
Since 0.5.8.4 --tile-background doesn't seem to work anymore

### ISSUE THREAD

**Issue by spudje** [DBuit/Homekit-panel-card#81]
After updating to 0.5.8.4, any changes made to --tile-background (and maybe other styles) don't have any effect :(

![image](https://user-images.githubusercontent.com/53037698/92210767-a38ecc00-ee8f-11ea-89cb-d4add030b2e6.png)

**Comment by DBuit** [comment]
Hi @spudje,

That is strange it is working for me in the new version..
Have you tried reinstalling the card? Maybe restart Home assistant and clear browser cache?

**Comment by spudje** [comment]
No sorry, it isn't working. Tried multiple browsers, multiple HASS themes, HASS restart, all the same :(

**Comment by wtrbuit** [comment]
@spudje is this still an issue for you? Looking at you screenshot it almost looks like you are missing the closing bracket for the CSS: `}`

This should work for example:
```
style: |
    :host {
        --tile-background: rgba(255, 0, 0, .5);
        --tile-on-background: rgba(255, 0, 0, 1);
    }
