### ISSUE TITLE
Refresh in Fullykiosk Browser

### ISSUE THREAD

**Issue by syedkami** [DBuit/Homekit-panel-card#84]
Hi. Using this component since long. Now having issue in fully kiosk browser that when you refresh, then all icons disappears, then after click on edit dashboard, these appears again. 
Kindly look into this. Thanks

**Comment by acateon** [comment]
Got a simular problem in Chrome... When reloading the page the first page/view is not rendered but the other ones are. Refreshing again solves it.

**Comment by JohannPie** [comment]
Got the same problem in fully and in Safari on my iPhone (ios 14)

**Comment by wtrbuit** [comment]
What version of HA are you running?

**Comment by JohannPie** [comment]
This is on the Most current version of HA, but it was also in the several last versions (happens since about 1 month ago I guess)

**Comment by wtrbuit** [comment]
@JohannPie are you on 0.117.1 of 0.117.2? I was running on a lower version and am updating now to see if it is fixed. It should be fixed in the newer versions and if not it will come with the first non patch release. I will keep an eye on it and report if I am no longer seeing the issue.

**Comment by JohannPie** [comment]
Actually I’m on 0.117.5 right now. Sometimes, if I reload the page, it says that it cannot find the custom element homekit panel card. Then, if I refresh again, everything is blank until I press the edit button and press „x“ out of edit mode. Then everything is back again, until I refresh the page, then it’s blank. This is the behavior right now in the iOS app and on fully kiosk (most recent version). Greetings,
Johann

**Comment by wtrbuit** [comment]
@JohannPie we spoke with Thomas Loven about this issue and he introduced a fix for the panel cards since that is the issue.

I checked and I hope the fix will come available with 0.117.6 or 0.117.7. The fix has been put in de Development branch of the Frontend of Home Assistent 7 days ago and in 0.117.5 there are additions from 10 days ago. 🤞 it will be here soon!

**Comment by JohannPie** [comment]
Thank you!

**Comment by JohannPie** [comment]
Still not resolved in 0.117.6 :( will the fix come in 0.117.7 then?
