### ISSUE TITLE
How can I install Homekit-panel-card

### ISSUE THREAD

**Issue by radek-foltyn** [DBuit/Homekit-panel-card#87]
Hi, I sorry, but i need ask you about manual installation Homekit-panel-card, because my HACS can not find Homekit-panel-card. Cay you tell me, what are the destionation of HA directory for Homekit-panel-card.
I have this bug
```
Custom element doesn't exist: homekit-card.
type: 'custom:homekit-card'
style: |
  :host {
    --tile-background: rgba(255, 255, 255, 0.8);
    --tile-border-radius: 12px;
    --tile-width: 100px;
    --tile-height: 100px;
    --tile-on-background: rgba(255, 255, 255, 1);...
```
thank you very much
R.

**Comment by wtrbuit** [comment]
Hi,

You can add the Homekit Panel Card as a custom repository in HACS like so:

![hacs-custom-repo](https://user-images.githubusercontent.com/2961836/98265145-08969900-1f89-11eb-8bdd-bb67d8f7d879.gif)

**Comment by wtrbuit** [comment]
Closing this issue. If you have any further questions please feel free to contact us.

**Comment by Neotastisch** [comment]
But if i add the example code there is an error

You need to define entities: or rows:
type: custom:homekit-card
